name: Create Bad Screenshots

on:
  push:
    branches:
      - main

jobs:
  screenshots:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver_manager

    - name: Create Bad Screenshots
      run: bad-image-getter.py.py
      
    - name: Upload Screenshots as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: badScreenshots
        path: ./badScreenshots/
